// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;


/// A concrete implementation of the coach mark arrow view and the default one provided by the library.
SWIFT_CLASS("_TtC12Instructions25CoachMarkArrowDefaultView")
@interface CoachMarkArrowDefaultView : UIImageView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class UITextView;
@class UIView;


/// A concrete implementation of the coach mark body view and the default one provided by the library.
SWIFT_CLASS("_TtC12Instructions24CoachMarkBodyDefaultView")
@interface CoachMarkBodyDefaultView : UIControl
@property (nonatomic, readonly, strong) UIControl * _Nullable nextControl;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, strong) UILabel * _Nonnull nextLabel;
@property (nonatomic, strong) UITextView * _Nonnull hintLabel;
@property (nonatomic, strong) UIView * _Nonnull separator;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame hintText:(NSString * _Nonnull)hintText nextText:(NSString * _Nullable)nextText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHintText:(NSString * _Nonnull)hintText nextText:(NSString * _Nullable)nextText;
@end



/// A concrete implementation of the coach mark skip view and the default one provided by the library.
SWIFT_CLASS("_TtC12Instructions24CoachMarkSkipDefaultView")
@interface CoachMarkSkipDefaultView : UIButton
@property (nonatomic, readonly, strong) UIControl * _Nullable skipControl;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;


/// Handles a set of coach marks, and display them successively.
SWIFT_CLASS("_TtC12Instructions20CoachMarksController")
@interface CoachMarksController : UIViewController

/// true if coach marks are curently being displayed, false otherwise.
@property (nonatomic, readonly) BOOL started;

/// Overlay fade animation duration
@property (nonatomic) NSTimeInterval overlayFadeAnimationDuration;

/// Background color of the overlay.
@property (nonatomic, strong) UIColor * _Nonnull overlayBackgroundColor;

/// true to let the overlay catch tap event and forward them to the CoachMarkController, false otherwise.
///
/// After receiving a tap event, the controller will show the next coach mark.
///
/// You can disable the tap on a case-by-case basis, see CoachMark.disableOverlayTap
@property (nonatomic) BOOL allowOverlayTap;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;

/// Will be called when the user perform an action requiring the display of the next coach mark.
///
/// \param sender the object sending the message
- (void)performShowNextCoachMark:(id _Nullable)sender;

/// Will be called when the user choose to skip the coach mark tour.
///
/// \param sender the object sending the message
- (void)skipCoachMarksTour:(id _Nullable)sender;

/// Start displaying the coach marks.
- (void)startOn:(UIViewController * _Nonnull)parentViewController;

/// Stop displaying the coach marks and perform some cleanup.
- (void)stop;

/// Pause the display. This method is expected to be used by the delegate to top the display, perform animation and resume display with play()
- (void)pause;

/// Resume the display. If the display wasn't paused earlier, this method won't do anything.
- (void)resume;

/// Show the next specified Coach Mark.
///
/// <ul><li>index if set, the index of the coach mark to show</li></ul>
- (void)showNextWithNumberOfCoachMarksToSkip:(NSInteger)numberToSkip;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
